### ISSUE TITLE
new great Control nearly every event for each world idea

### ISSUE THREAD

**Issue by brexmania123** [survanetwork/Worlds#31] opened 2018-02-07 16:12 UTC
Hi i would like to submit an idea you could add to "Control nearly every event for each world". you could make it so you can enable and disable certain plugin commands on the different worlds making it possible to have worlds based off of an gamemode like factions, smp, anarchy, skyblock, ext without having more than 1 server running.

**Comment by jarne** [comment] 2018-02-07 16:32
Thanks for the feedback, I think it's a duplicate of #22.

**Closed by jarne** 2018-02-07 16:32 UTC
